# Generated by Django 3.2.6 on 2021-09-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20210903_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='url',
            field=models.URLField(default='www.google.com', max_length=255),
            preserve_default=False,
        ),
    ]
